### PR TITLE
Add Dockerfile and function to run it as executable

### PR DESCRIPTION
**Pull request by jrm16020**

### CODE REVIEW

**Comment by jrm16020** [comment]
The idea behind the shell functions is to include something like this in .bashrc

`if [[ -d $HOME/.bash_functions ]]; then
  for file in $HOME/.bash_functions/*; do
    . $file
  done
fi`

**Comment by gregglind** [comment]
Hello!  Newb to docker and such.   please explain the (maybe obvious?) use case for all this?  I has confused, but am educable!

**Review by gregglind — CHANGES_REQUESTED** [review]
Mostly a 'needs-info' because i don't know all this Docker business :)  Help me say yes, especially if it means I will never have to do any work or maintain it!

**Comment by jrm16020** [comment]
This comes specifically from the desire to include testing like this in a CI/CD pipeline.  Having the observatory CLI tool in a container means that I don't have to add software to my Jenkins master or agent to execute Observatory; it only needs to be able to run containers.

A side benefit is that this would compliment the containerized [http-observatory](https://github.com/mozilla/http-observatory).  If everything is in a container, I can get my developers to adopt its use by executing a few easy commands without installing extra software to their host operating system.  

Does that help?  I'm happy to prove further justification as needed.

**Comment by jrm16020** [comment]
@gregglind I also added Bash completion to the PR.

**Comment by gregglind** [comment]
Thanks!  I mostly wanted to make sure this was an enhancement that I had to do nothing for :)  If it breaks, I will send them right to you :)

Thanks for the PR!

GL

**Comment by jrm16020** [comment]
I'm happy to send it!  We need more tools like this one!

**Comment by gregglind** [comment]
(npm package of 0.6.5 has this.  A few bugs to fix for 0.7.0 though, maybe today or tomorrow)

**Comment by gregglind** [comment]
(sorry for another request... mind posting a little blurb here for the 'README' to describe docker mode / usage?  Maybe it's obvious for Docker people :) )

see #22

**Pull request merged**
